sudo: required

services:
- docker

language: java

jdk:
  - openjdk11

env:
  global:
    - IMAGE_NAME=catalogues

script:
  - mvn clean package
  - docker build -t "$IMAGE_NAME" .

before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"

deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest"
  on:
    branch: master