apiVersion: v1
kind: Service
metadata:
  labels:
    app: catalogues
  name: catalogues
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: catalogues